return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I should wait until he's asleep.",
			GENERIC = "Nothing that I can shave here.",
			NOBITS = "Not even any prickly stubble!",
		},
		STORE =
		{
			GENERIC = "There's not enough room.",
			NOTALLOWED = "I can't place that in there.",
		},
	},
	ACTIONFAIL_GENERIC = "I'm not allowed to do that.",
	ANNOUNCE_ADVENTUREFAIL = "Maxwell, you're a thorn in my side.",
	ANNOUNCE_BEES = "They just want to pollinate me.",
	ANNOUNCE_BOOMERANG = "Spikes!  I should catch that nest time...",
	ANNOUNCE_CHARLIE = "What the quill was that?!",
	ANNOUNCE_CHARLIE_ATTACK = "OUCH!  That hurt both of us!",
	ANNOUNCE_COLD = "Brrr...  Need warm...",
	ANNOUNCE_HOT = "I love summer!",
	ANNOUNCE_CRAFTING_FAIL = "I need to collect more ingredients.",
	ANNOUNCE_DEERCLOPS = "I hear something in the distance...",
	ANNOUNCE_DUSK = "The sun's going down.  It'll be back tomorrow.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Delicious!",
		PAINFUL = "I have a sharp pain in my stomach.",
		SPOILED = "Ick!  Rotten!",
		STALE = "I'm glad I didn't wait any longer.",
		INVALID = "I can't eat something like that!",
	},
	ANNOUNCE_ENTER_DARK = "Spikes alive!  I can't see!",
	ANNOUNCE_ENTER_LIGHT = "Hey, I can see again!",
	ANNOUNCE_FREEDOM = "I'm free!  On to the next location!",
	ANNOUNCE_HIGHRESEARCH = "The knowledge is rooted firmly in my head!",
	ANNOUNCE_HOUNDS = "Uh-oh, that doesn't sound good...",
	ANNOUNCE_HUNGRY = "What I wouldn't give for a nice burrito right now.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "It's a fresh track, which means fresh meat!",
	ANNOUNCE_HUNT_LOST_TRAIL = "No more tracks.  Looks like it got away.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "The ground is too wet for the footprints to stay.",
	ANNOUNCE_INV_FULL = "I've gotta make some room first!",
	ANNOUNCE_KNOCKEDOUT = "Whoa, some party, huh?",
	ANNOUNCE_LOWRESEARCH = "Funny, I don't feel any smarter.",
	ANNOUNCE_MOSQUITOS = "Shoo!  I don't have any blood!",
	ANNOUNCE_NODANGERSLEEP = "I don't sleep well when I'm being hunted.",
	ANNOUNCE_NODAYSLEEP = "It's such a nice day.  No need to waste it in bed.",
	ANNOUNCE_NODAYSLEEP_CAVE = "I don't want to sleep down here.",
	ANNOUNCE_NOHUNGERSLEEP = "I need a bite to eat before I can sleep.",
	ANNOUNCE_NOSLEEPONFIRE = "No.  I'm not sleeping on something that is on fire.",
	ANNOUNCE_NODANGERSIESTA = "There's too much danger to rest now!",
	ANNOUNCE_NONIGHTSIESTA = "I need to build a tent or something if I'm going to sleep.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "I'd be too restless down here.",
	ANNOUNCE_NOHUNGERSIESTA = "I'm too hungry for a siesta!",
	ANNOUNCE_NO_TRAP = "That wasn't hard at all.",
	ANNOUNCE_PECKED = "Ouch!  Yeah, you like those spines?!",
	ANNOUNCE_QUAKE = "That's not just me that's trembling...",
	ANNOUNCE_RESEARCH = "Always strive for a sharp wit!",
	ANNOUNCE_SHELTER = "I appreciate the shelter, tree.",
	ANNOUNCE_THORNS = "Ow!  Is that what it feels like?",
	ANNOUNCE_BURNT = "OUCH! HOT HOT HOT!",
	ANNOUNCE_TORCH_OUT = "Oh-no, my torch burned out!",
	ANNOUNCE_TRAP_WENT_OFF = "Darn it.",
	ANNOUNCE_UNIMPLEMENTED = "Ouch!  This isn't ready yet.",
	ANNOUNCE_WORMHOLE = "I bet that hurt going all the way down.",
	ANNOUNCE_CANFIX = "\nI can repair it, too!",
	ANNOUNCE_ACCOMPLISHMENT = "I never thought I could accomplish so much!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "I am the king of cacti!",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "You need more fertilizer, don't you?",
	ANNOUNCE_TOOL_SLIP = "Augh!  I can't hold onto it!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "GOODNESS!  That was close!",
	
	ANNOUNCE_DAMP = "It's just a little water...",
	ANNOUNCE_WET = "Brrr...  I'm starting to get chilly.",
	ANNOUNCE_WETTER = "It's VERY possible to over-water a cactus!",
	ANNOUNCE_SOAKED = "I'm soaked to my spines!",
	
	BATTLECRY =
	{
		GENERIC = "You're gonna feel a little prick!",
		PIG = "Yeah, come hit me!",
		PREY = "You will be my dinner!",
		SPIDER = "Feel my spiky wrath, spider!",
		SPIDER_WARRIOR = "Let's dance, ugly!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Mess with the plant, get the thorns.",
		PIG = "That's right, run away!",
		PREY = "I'm not exactly built for speed.",
		SPIDER = "Good, get away from me.",
		SPIDER_WARRIOR = "Go on!  Get out of here!",
	},
	DESCRIBE =
	{
        GLOMMER = "It's adorable!",
        GLOMMERFLOWER = "I still think my flower is better.",
        GLOMMERWINGS = "Too bad I can't fly with them.",
        GLOMMERFUEL = "Is this stuff even safe to eat?",
        BELL = "Ding dong!  Come in!",
        STATUEGLOMMER = 
        {	
        	GENERIC = "I think its supposed to be abstract art.",
        	EMPTY = "Now we'll never know what it was.",
    	},

		WEBBERSKULL = "Poor little guy. He deserves a proper funeral.",
		WORMLIGHT = "I have a sudden urge to eat this.",
		WORM =
		{
		    PLANT = "It's just a glowy plant.",
		    DIRT = "Yep. that's dirt.",
		    WORM = "That's a big worm!",
		},
		MOLE =
		{
			UNDERGROUND = "There's something under there...",
			ABOVEGROUND = "Lemme whack that moleworm!",
		},
		MOLEHILL = "Man, talk about a hole-in-the-ground.",
		MOLEHAT = "At least I can't smell it.",

		EEL = "I'm not a fan of seafood, but it'll do.",
		EEL_COOKED = "It smells slightly better than before.",
		UNAGI = "I hear this is all the rage in another country.",
		EYETURRET = "Don't poke yourself on me.",
		EYETURRET_ITEM = "I should be careful about handling it.",
		MINOTAURHORN = "I am insanely jealous.",
		MINOTAURCHEST = "Is it good or bad?  It could go either way.",
		THULECITE_PIECES = "Some small pieces of thulecite.",
		POND_ALGAE = "It's pond algae!",
		GREENSTAFF = "I can use this.",
		POTTEDFERN = "Sometimes I think about settling down myself.",

		THULECITE = "This stuff is crazy hard.",
		ARMORRUINS = "It's not as heavy as I thought.",
		RUINS_BAT = "Boy, this is heavy.",
		RUINSHAT = "A perfect frame for my flower!",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "Seems fairly calm.",
		WARN = "I can feel the magic building up...",
		WAXING = "The magic is getting stronger!",
		STEADY = "The magic is at a steady rate, I believe.",
		WANING = "I think the magic is going down.",
		DAWN = "It's almost over!",
		NOMAGIC = "I don't sense any magic.",
		},
		BISHOP_NIGHTMARE = "He's seen better days.",
		ROOK_NIGHTMARE = "Boy, that's scary.",
		KNIGHT_NIGHTMARE = "Boy, that thing looks run-down.",
		MINOTAUR = "It looks like he's mad at me.",
		SPIDER_DROPPER = "Those spiders are in for a nasty surprise.",
		NIGHTMARELIGHT = "I wonder what this was used for?",
		NIGHTSTICK = "A glowy light weapon!",
		GREENGEM = "It's my favorite color!",
		RELIC = "A relic from the past.",
		RUINS_RUBBLE = "This looks broken, but I think I could fix it.",
		MULTITOOL_AXE_PICKAXE = "Now I could even harvest petrified wood!",
		ORANGESTAFF = "Where has this been all my life?",
		YELLOWAMULET = "Feels nice and warm.",
		GREENAMULET = "Now this is a snazzy look.",
		SLURPERPELT = "Looks like an old soggy blanket.",	

		SLURPER = "I've heard that spines don't bother them...",
		SLURPER_PELT = "Looks like an old soggy blanket.",
		ARMORSLURPER = "It feels wet and nasty, but I kinda like it.",
		ORANGEAMULET = "Now this is a look I could get used to.",
		YELLOWSTAFF = "It's my own personal staff.",
		YELLOWGEM = "Reminds me of the desert sun.",
		ORANGEGEM = "It reminds me of a desert sunset.",
		TELEBASE = 
		{
			VALID = "Yup, it's ready to use.",
			GEMS = "I have to add more purple gems first.",
		},
		GEMSOCKET = 
		{
			VALID = "It looks ready to me.",
			GEMS = "I have to put a gem here.",
		},
		STAFFLIGHT = "Doesn't really seem all that safe.",
	
        ANCIENT_ALTAR = "Looks strange and mysterious.",

        ANCIENT_ALTAR_BROKEN = "This appears broken.",

        ANCIENT_STATUE = "What horrid décor.",

        LICHEN = "I certainly couldn't grow here.",
		CUTLICHEN = "Full of vitamins, but burns off fast.",

		CAVE_BANANA = "Looks more like a plantain to me.",
		CAVE_BANANA_COOKED = "Now it's even more mushy.",
		CAVE_BANANA_TREE = "How do you even grow down here?",
		ROCKY = "There's a song that comes to mind, but the name escapes me.",
		
		COMPASS =
		{
			GENERIC="I can't read it yet.",
			N = "North",
			S = "South",
			E = "East",
			W = "West",
			NE = "Northeast",
			SE = "Southeast",
			NW = "Northwest",
			SW = "Southwest",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "The magic is getting stronger!",
			STEADY = "The magic is at a steady rate, I believe.",
			WANING = "I think the magic is going down.",
			DAWN = "It's almost over!",
			WARN = "I can feel the magic building up...",
			CALM = "Seems fairly calm.",
			NOMAGIC = "I don't sense any magic.",
		},

		HOUNDSTOOTH="It's sharp, but I'm sharper.",
		ARMORSNURTLESHELL="I welcome the extra protection.",
		BAT="Flying abomination!",
		BATBAT = "Vaguely vampiric.",
		BATWING="Your flying days are over.",
		BATWING_COOKED="There's really not much meat.",
		BEDROLL_FURRY="It's nice and warm, but it's hard to get out of.",
		BUNNYMAN="Thankfully, I am not a carrot.",
		FLOWER_CAVE="I wish my flower could do that.",
		FLOWER_CAVE_DOUBLE="I wish my flower could do that.",
		FLOWER_CAVE_TRIPLE="I wish my flower could do that.",
		GUANO="I hear people make this into coffee.  Not me, though.",
		LANTERN="A torch doesn't even hold a candle to this!",
		LIGHTBULB="I could eat it, but it makes better fuel.",
		MANRABBIT_TAIL="It's so fluffy!",
		MUSHTREE_TALL  ="Now that is a big mushroom!",
		MUSHTREE_MEDIUM="I wonder how old these are?",
		MUSHTREE_SMALL ="That's not an ordinary mushroom.",
		RABBITHOUSE=
		{
			GENERIC = "This seems like a healthy obsession.",
			BURNT = "And now it's a cooked carrot.",
		},
		SLURTLE="It eats rocks.",
		SLURTLE_SHELLPIECES="It was more useful when it was whole.",
		SLURTLEHAT="I hope my flower doesn't get slimy.",
		SLURTLEHOLE="I bet it's all wet and slippery in there.",
		SLURTLESLIME="It's really gross.",
		SNURTLE="This is also gross.",
		SPIDER_HIDER="Great, more spiders.",
		SPIDER_SPITTER="Keep your spit to yourself!",
		SPIDERHOLE="I wonder if anything still lives here.",
		STALAGMITE="It's just a rock.",
		STALAGMITE_FULL="It's just a rock.",
		STALAGMITE_LOW="It's just a rock.",
		STALAGMITE_MED="It's just a rock.",
		STALAGMITE_TALL="Some more rocks.",
		STALAGMITE_TALL_FULL="Some more rocks.",
		STALAGMITE_TALL_LOW="Some more rocks.",
		STALAGMITE_TALL_MED="Some more rocks.",

		TURF_CARPETFLOOR = "It has a nice plush feet under my roots.",
		TURF_CHECKERFLOOR = "It makes me feel like a king.",
		TURF_DIRT = "Good ol' fashioned dirt.",
		TURF_FOREST = "Ground from the forest.",
		TURF_GRASS = "They don't make grass like this anymore.",
		TURF_MARSH = "Wet and soppy ground.",
		TURF_ROAD = "I took the road less traveled and put it in my pocket.",
		TURF_ROCKY = "It's a rocky road.",
		TURF_SAVANNA = "It's an old pioneer trick.",
		TURF_WOODFLOOR = "Nothing beats the hardwood.",

		TURF_CAVE="It's a souvenir.",
		TURF_FUNGUS="Careful not to breathe in the spores.",
		TURF_SINKHOLE="It gives me a sinking feeling.",
		TURF_UNDERROCK="More rocky turf.",
		TURF_MUD="I actually like mud pies.",
		
		TURF_DECIDUOUS = "It's tightly-packed leaf litter.",
		TURD_SANDY = "It's like a little piece of home.",
		TURF_BADLANDS = "They're not called 'goodlands', you know.",

		POWCAKE = "It doesn't seem natural.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Is that rock blocking something?",
            OPEN = "This hole in the ground begs to be explored.",
        },
        CAVE_EXIT = "I miss the sunshine.",
		MAXWELLPHONOGRAPH = "Personally, I prefer mambo.",
		BOOMERANG = "Crikey spiky!",
		PIGGUARD = "He takes his job very seriously.",
		ABIGAIL = "Would that bow look good on me?",
		ADVENTURE_PORTAL = "Many challenges await!  Look sharp!",
		AMULET = "I feel wilt-proof!",
		ANIMAL_TRACK = "Animal tracks, from feet with meat.",
		ARMORGRASS = "It doesn't seem very practical.",
		ARMORMARBLE = "It's really heavy.",
		ARMORWOOD = "This seems wrong on many different levels.",
		ARMOR_SANITY = "For those who prefer matter over mind.",
		ASH =
		{
			GENERIC = "The charred skeleton left behind by cruel fire.",
			REMAINS_GLOMMERFLOWER = "When I teleported, the flower burned up!",
			REMAINS_EYE_BONE = "The eyebone burnt up during teleportation!",
			REMAINS_THINGIE = "It's burnt up now, but it wasn't always like this.",
		},
		AXE = "Cutting edge wilderness survival.",
		BABYBEEFALO = "It's not big enough to eat yet.",
		BACKPACK = "I can carry more this way.",
		BACONEGGS = "Cacti don't have cholesterol.",
		BANDAGE = "Maybe it won't attract ants?",
		BASALT = "There's no breaking through that!",
		BATBAT = "Just imagine if I were prickly AND could fly.",
		BEARDHAIR = "From someone else's face.",
		BEARGER = "What a monstrosity!",
		BEARGERVEST = "I'm ready for the longest, coldest winter ever!",
		ICEPACK = "It keeps a steady temperature.",
		BEARGER_FUR = "Fur from the ferocious bearger.",
		BEDROLL_STRAW = "I'm sharing a cot with mushrooms.",
		BEE =
		{
			GENERIC = "They tickle my flower.",
			HELD = "You have a stinger?  That's cute.",
		},
		BEEBOX =
		{
			FULLHONEY = "Look at all of that honey!",
			GENERIC = "A box full of busy bees.",
			NOHONEY = "I should come back when there's more honey.",
			SOMEHONEY = "There's a little honey in it.",
			BURNT = "I don't like ashes in my honey.",
		},
		BEEFALO =
		{
			FOLLOWER = "He looks tired.",
			GENERIC = "You don't see many beefalo in the desert.",
			NAKED = "It makes me glad that I don't have hair.",
			SLEEPING = "They don't wake easily.",
		},
		BEEFALOHAT = "I feel like a viking!",
		BEEFALOWOOL = "I'm sure it smells terrible.",
		BEEHAT = "Spikes, AND a net.",
		BEEHIVE = "A bunch of busy bees.",
		BEEMINE = "I like it.",
		BEEMINE_MAXWELL = "Mosquitoes in a bottle.",
		BERRIES = "I suppose these are like bush eggs.",
		BERRIES_COOKED = "They're all mushy now.",
		BERRYBUSH =
		{
			BARREN = "Needs some fertilizer.",
			WITHERED = "They're not suited for summer like me.",
			GENERIC = "A bush laden with berries.",
			PICKED = "Now I feel bad.",
		},
		BIGFOOT = "Holy mackerel!  What a giant!",
		BIRDCAGE =
		{
			GENERIC = "Avian penitentiary.",
			OCCUPIED = "This bird is my prisoner.",
			SLEEPING = "Lights out, jailbird!",
		},
		BIRDTRAP = "Used to capture birds, apparently.",
		BIRD_EGG = "Has the potential to be something great, like breakfast.",
		BIRD_EGG_COOKED = "The only thing better than sun is sunny-side up!",
		BISHOP = "I never liked chess.",
		BLOWDART_FIRE = "It's an abomination against nature.",
		BLOWDART_SLEEP = "Makes me tired just thinking about it.",
		BLOWDART_PIPE = "Now I can launch sharp objects at things!  Hooray!",
		BLUEAMULET = "Chilly.",
		BLUEGEM = "It feels cold when I touch it.",
		BLUEPRINT = "Instantaneous knowledge!",
		BELL_BLUEPRINT = "The instructions ring a bell.",
		BLUE_CAP = "A blue mushroom.",
		BLUE_CAP_COOKED = "A cooked blue mushroom.",
		BLUE_MUSHROOM =
		{
			GENERIC = "This is a mushroom, I think.",
			INGROUND = "You've gotta come out sometime.",
			PICKED = "Don't worry, it'll grow back.",
		},
		BOARDS = "Planks of wood.",
		BOAT = "I bet it's full of holes.",
		BONESHARD = "Tiny shards of bone.",
		BONESTEW = "Made with meat, meat, and more meat.",
		BUGNET = "I ought to start a collection.",
		BUSHHAT = "It's like a piggyback ride for the bush.",
		BUTTER = "I don't understand it, but I'm not complaining.",
		BUTTERFLY =
		{
			GENERIC = "Gentle pollinators.",
			HELD = "You've fallen into my trap!",
		},
		BUTTERFLYMUFFIN = "Thanks for pollinating me, sucker!",
		BUTTERFLYWINGS = "One for each hole.",
		BUZZARD = "I used to see these all the time back home.",
		CACTUS = 
		{
			GENERIC = "A lesser relative of mine.",
			PICKED = "I am the better cactus.",
		},
		CACTUS_MEAT_COOKED = "This is a little bit sick.",
		CACTUS_MEAT = "Probably deserved it.",
		CACTUS_FLOWER = "It's my flower now.",

		COLDFIRE =
		{
			EMBERS = "It's starting to get warm.",
			GENERIC = "At least I can use it for light.",
			HIGH = "BRR!  COLD!",
			LOW = "The cold fire is getting low.",
			NORMAL = "It's burning at a steady cold rate.",
			OUT = "So much for the cold fire.",
		},
		CAMPFIRE =
		{
			EMBERS = "The fire needs another victim, quickly!",
			GENERIC = "Just don't get too close.",
			HIGH = "Stand back!  It's too hot!",
			LOW = "The flames are starting to dim.",
			NORMAL = "That feels nice.",
			OUT = "So much for that.",
		},
		CANE = "I never realized how hard walking was!",
		CATCOON = "He's a real cutie.",
		CATCOONDEN = 
		{
			GENERIC = "Where on earth did they get yarn?",
			EMPTY = "Looks like the catcoon won't be coming back.",
		},
		CATCOONHAT = "It's a hat from up north!",
		CARROT = "Tubular!",
		CARROT_COOKED = "Now all we need are some mushy peas.",
		CARROT_PLANTED = "It almost feels wrong to pluck it.  Almost.",
		CARROT_SEEDS = "Plant these and I'll get carrots.",
		WATERMELON_SEEDS = "Watermelon seeds.",
		CAVE_FERN = "Ancient plants.",
		CHARCOAL = "Burned remains, ready to be burned again.",
        CHESSJUNK1 = "Chess pieces are better off broken.",
        CHESSJUNK2 = "Chess pieces are better off broken.",
        CHESSJUNK3 = "Chess pieces are better off broken.",
		CHESTER = "You get to carry my stuff.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Watch which end you pick up.",
			WAITING = "Did I poke it out?",
		},
		COOKEDMANDRAKE = "This feels like murder.",
		COOKEDMEAT = "Mmmm.  Delicious.",
		COOKEDMONSTERMEAT = "Still doesn't look very appetizing.",
		COOKEDSMALLMEAT = "A yummy little morsel.",
		COOKPOT =
		{
			COOKING_LONG = "I should find something to occupy my time.",
			COOKING_SHORT = "Not much longer now.",
			DONE = "Oh boy, I'm starved!",
			EMPTY = "We're both hollow, pot.",
			BURNT = "I can't cook in a cooked pot.",
		},
		CORN = "This is very hard for me to eat.",
		CORN_COOKED = "At least it can't get stuck in my teeth.",
		CORN_SEEDS = "Some kernels of corn.",
		CROW =
		{
			GENERIC = "A dark bird.",
			HELD = "He'd rather be free.  Too bad.",
		},
		CUTGRASS = "I claim this grass.",
		CUTREEDS = "I could make some neat things out of this.",
		CUTSTONE = "About as sharp as a brick.",
		DEADLYFEAST = "I wouldn't eat that.",
		DEERCLOPS = "A one-eyed deer?!",
		DEERCLOPS_EYEBALL = "I poked the eye out!",
		EYEBRELLAHAT =	"It's keeping an eye out on the weather.",
		DEPLETED_GRASS =
		{
			GENERIC = "This used to be grass once.",
		},
		DEVTOOL = "Feels all-powerful.",
		DEVTOOL_NODEV = "Not enough experience to wield it.",
		DIRTPILE = "Isn't it just a pile of dirt?",
		DIVININGROD =
		{
			COLD = "There's only a tiny signal.",
			GENERIC = "I bet this will help me out.",
			HOT = "I'm spicy-hot!",
			WARM = "Looks like this is the right way to go.",
			WARMER = "The signal is pretty strong.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "It's a base for a divining rod.",
			READY = "It needs a key of some sort.",
			UNLOCKED = "Fully operational!",
		},
		DIVININGRODSTART = "Now THAT looks useful!",
		DRAGONFLY = "Oh gracious, it spits fire!",
		ARMORDRAGONFLY = "My trophy is also my protection.",
		DRAGON_SCALES = "The scales weigh in my favor.",
		DRAGONFLYCHEST = "This chest is best.",
		LAVASPIT = 
		{
			HOT = "HOT HOT HOT!",
			COOL = "At least it's not hot anymore.",
		},
		DRAGONFRUIT = "I hope it doesn't breath fire.",
		DRAGONFRUIT_COOKED = "A dragon that's weak to fire.",
		DRAGONFRUIT_SEEDS = "Dragonfruit seeds!",
		DRAGONPIE = "I am one heck of a baker.",
		DRUMSTICK = "Time to get a leg-up on hunger!",
		DRUMSTICK_COOKED = "It's not gamey at all!",
		DUG_BERRYBUSH = "Time to give this bush a new home.",
		DUG_GRASS = "Time to give this grass a new home.",
		DUG_MARSH_BUSH = "I dug up a marsh bush.",
		DUG_SAPLING = "Every day should be Earth Day, I guess.",
		DURIAN = "I've been told it smells like a rotting corpse.",
		DURIAN_COOKED = "Luckily, I don't have a nose.",
		DURIAN_SEEDS = "Stinky seeds that grow stinky fruit.",
		EARMUFFSHAT = "Now all I need are some ears.",
		EGGPLANT = "It's rumoured to have magical properties.",
		EGGPLANT_COOKED = "Nothing magical about this.",
		EGGPLANT_SEEDS = "Which came first, the eggplant or the seed?",
		DECIDUOUSTREE = 
		{
			BURNING = "It's a forest fire!",
			BURNT = "That could've been me!",
			CHOPPED = "It's my wood now!",
			POISON = "I don't think it liked that I stole those birchnuts!",
			GENERIC = "Leafy trees that change beautifully in the fall.",
		},
		ACORN = 
		{
		    GENERIC = "A tough nut to crack.",
		    PLANTED = "Grow into a big strong tree.",
		},
		ACORN_COOKED = "Roasted birchnuts!  Mmm!",
		BIRCHNUTDRAKE = "He seems upset.",
		EVERGREEN =
		{
			BURNING = "It's a forest fire!",
			BURNT = "That could've been me!",
			CHOPPED = "It's my wood now!",
			GENERIC = "You call those needles?",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "It's a forest fire!",
			BURNT = "That could've been me!",
			CHOPPED = "It's my wood now!",
			GENERIC = "It's a sterile tree.",
		},
		EYEPLANT = "Is it an eye, or a mouth?",
		FARMPLOT =
		{
			GENERIC = "I should try to plant something.",
			GROWING = "Grow faster!",
			NEEDSFERTILIZER = "It could use some fertilizer.",
			BURNT = "Nothing will grow in a burnt plot.",
		},
		FEATHERHAT = "Behold!  The rare spiked bird!",
		FEATHER_CROW = "It's dark, like the night.",
		FEATHER_ROBIN = "Red as a summer sunset.",
		FEATHER_ROBIN_WINTER = "Just looking at it give me the chills.",
		FEM_PUPPET = "Looks like she's trapped!",
		FIREFLIES =
		{
			GENERIC = "I should catch them in a net!",
			HELD = "Don't let them loose.",
		},
		FIREHOUND = "That one starts fires!",
		FIREPIT =
		{
			EMBERS = "The fire is almost dead.",
			GENERIC = "It's a lot safer than a campfire.",
			HIGH = "I'm glad it's closed off!",
			LOW = "The fire could use some more fuel.",
			NORMAL = "Feels warm and cozy.",
			OUT = "Thankfully, I can start it back up.",
		},
		COLDFIREPIT =
		{
			EMBERS = "It's nearly out.",
			GENERIC = "Renewable cold.  Yay.",
			HIGH = "I'm going to become a cactus-sicle!",
			LOW = "It's low, but still cold.",
			NORMAL = "It's at a steady rate of cooling.",
			OUT = "Good riddance.",
		},
		FIRESTAFF = "It's best not to play with it.",
		FIRESUPPRESSOR = 
		{	
			ON = "As long as you don't fling it on me.",
			OFF = "That's enough ice for now.",
			LOWFUEL = "I need to refuel this thing.",
		},

		FISH = "I don't care much for seafood, but a meal is a meal.",
		FISHINGROD = "A crude fish snare.",
		FISHSTICKS = "Now they're in the river Stix.",
		FISHTACOS = "I love tacos, but I'd rather not have fish.",
		FISH_COOKED = "At least it's easier to eat now.",
		FLINT = "Time to make some tools.",
		FLOWER = "Mine smells better, in my opinion.",
		FLOWERHAT = "Now I have more flowers than any cactus!",
		FLOWER_EVIL = "Nope, I don't like it.",
		FOLIAGE = "I suppose roughage is important.",
		FOOTBALLHAT = "Funny, nobody ever wants to tackle me.",
		FROG =
		{
			DEAD = "He's up in froggy heaven now.",
			GENERIC = "Don't let his looks fool you, he's vicious.",
			SLEEPING = "I'd rather take dead, but sleeping is tolerable.",
		},
		FROGGLEBUNWICH = "At least now I can't taste the frog legs.",
		FROGLEGS = "I've heard this is big in another country.",
		FROGLEGS_COOKED = "So, does chicken taste like frog?",
		FRUITMEDLEY = "A mixture of many plant's hopes and dreams.",
		GEARS = "I'm sure I could make something with these.",
		GHOST = "Is it that time of the year already?",
		GOLDENAXE = "Now I can cut down trees in style.",
		GOLDENPICKAXE = "What could go wrong?",
		GOLDENPITCHFORK = "Such a glorious yard-tool.",
		GOLDENSHOVEL = "Now I can dig holes and look good doing it!",
		GOLDNUGGET = "I rarely see gold back home.",
		GRASS =
		{
			BARREN = "I should fertilize it.",
			WITHERED = "It's too hot for it to grow back now.",
			BURNING = "Eep!  Look at it burn!",
			GENERIC = "It's just some grass.",
			PICKED = "I'll have to wait for it to grow back.",
		},
		GREEN_CAP = "A green mushroom.",
		GREEN_CAP_COOKED = "A cooked green mushroom.",
		GREEN_MUSHROOM =
		{
			GENERIC = "This is a mushroom, I think.",
			INGROUND = "You've gotta come out sometime.",
			PICKED = "Don't worry, it'll grow back.",
		},
		GUNPOWDER = "It really packs a wallop.",
		HAMBAT = "Strangely enough, it works.",
		HAMMER = "Hammers usually build things, not destroy them.",
		HEALINGSALVE = "It's gonna burn a little.",
		HEATROCK =
		{
			FROZEN = "It's even colder than ice!",
			COLD = "It's like ice.",
			GENERIC = "I bet this'll feel nice if I heat it up.",
			WARM = "It's nice and warm.",
			HOT = "Feels hot!",	
		},
		HOME = "I think someone lives here.",
		HOMESIGN =
		{
			GENERIC = "It's just a bunch of scribbling on a plank.",
			BURNT = "I couldn't read it before, let alone now.",
		},
		HONEY = "Thanks, bees!",
		HONEYCOMB = "I have evicted the bees.",
		HONEYHAM = "If I had a mouth, it would be watering.",
		HONEYNUGGETS = "Just the right size to fit.",
		HORN = "I don't hear anything.",
		HOUND = "Mangy mutt!",
		HOUNDBONE = "It's a bone.",
		HOUNDMOUND = "It's a hound's nest.",
		ICEBOX = "This will keep my food fresh.",
		ICEHAT = "I've got an ice hat.",
		ICEHOUND = "Great, more hounds.",
		INSANITYROCK =
		{
			ACTIVE = "I think my sanity is starting to suffer.",
			INACTIVE = "It looks as if it's embedded in the ground.",
		},
		JAMMYPRESERVES = "It's really just a bunch of mashed-up berries.",
		KABOBS = "I'm all about skewering things!",
		KILLERBEE =
		{
			GENERIC = "Gah!  Get away!",
			HELD = "It seems the tables have turned, bee.",
		},
		KNIGHT = "A mechanical horse?",
		KOALEFANT_SUMMER = "It's cute, but I'm too hungry to care.",
		KOALEFANT_WINTER = "Give me your meat!",
		KRAMPUS = "Hey, that's my stuff!",
		KRAMPUS_SACK = "To the victor go the spoils.",
		LEIF = "I'm pretty sure we're related, actually.",
		LEIF_SPARSE = "I'm pretty sure we're related, actually.",
		LIGHTNING_ROD =
		{
			CHARGED = "It's a shame I can't put this electricity to use.",
			GENERIC = "This will prevent stray bolts from hitting me.",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "They're actually pretty adorable.",
			CHARGED = "I wouldn't like getting struck by lightning either.",
		},
		LIGHTNINGGOATHORN = "What an odd design for a horn.",
		GOATMILK = "It's full of vitamin D and static!",
		LITTLE_WALRUS = "It's only a matter of time before he's a killer.",
		LIVINGLOG = "What are the consequences of burning this?",
		LOCKEDWES = "Looks like he's trapped by Maxwell's statues.",
		LOG =
		{
			BURNING = "YEOWCH!  HOT!",
			GENERIC = "Cut pieces of a tree.",
		},
		LUREPLANT = "I'm not falling for that old trick.",
		LUREPLANTBULB = "Plant it and watch the fun.",
		MALE_PUPPET = "Looks like he's trapped!",
		MANDRAKE =
		{
			DEAD = "His loss is my gain.",
			GENERIC = "Mandrakes have mysterious properties...",
			PICKED = "For the last time, we are NOT related!",
		},
		MANDRAKESOUP = "It's not cannibalism, we're not related.",
		MANDRAKE_COOKED = "Looks like he doesn't like fire either.",
		MARBLE = "That's some high-quality material.",
		MARBLEPILLAR = "It's too fancy for its own good.",
		MARBLETREE = "Looks like they can't speak for themselves.",
		MARSH_BUSH =
		{
			BURNING = "Wow, look at it go!",
			GENERIC = "It's got spikes, but that doesn't make it cool.",
			PICKED = "Okay, it's pointy enough to hurt.",
		},
		MARSH_PLANT = "A marsh plant.",
		MARSH_TREE =
		{
			BURNING = "Now, do I believe in karma?",
			BURNT = "A spiky skeleton.",
			CHOPPED = "See my spikes and tremble!",
			GENERIC = "I've seen sharper spikes.",
		},
		MAXWELL = "Hey, you're the jerk who started all this!",
		MAXWELLHEAD = "He should look into some wrinkle cream.",
		MAXWELLLIGHT = "They make me uneasy.",
		MAXWELLLOCK = "I think this is a lock of some sort.",
		MAXWELLTHRONE = "That looks uncomfortable, even to me.",
		MEAT = "I'm part carnivorous plant, on my mother's side.",
		MEATBALLS = "Tiny little balls of meat!",
		MEATRACK =
		{
			DONE = "It's done drying.",
			DRYING = "This is going to take a while to dry.",
			DRYINGINRAIN = "This won't dry in the rain.",
			GENERIC = "Time to dry some meats.",
			BURNT = "There's no more drying on this rack.",
		},
		MEAT_DRIED = "Devoid of moisture.",
		MERM = "You're about as ugly as they come.",
		MERMHEAD = 
		{
			GENERIC = "Well, this neighborhood looks friendly.",
			BURNT = "At least I can't smell it.",
		},
		MERMHOUSE = 
		{
			GENERIC = "It could use a coat of paint, and a bulldozer.",
			BURNT = "It's not a huge loss, really.",
		},
		MINERHAT = "It'll help me keep a sharp eye out in the dark.",
		MONKEY = "Speak no evil, monkey.",
		MONKEYBARREL = "A barrel?",
		MONSTERLASAGNA = "I'd get nasty heartburn if I had a heart.",
		FLOWERSALAD = "It makes for an interesting trophy.",
        ICECREAM = "I like the flavor, but it makes me cold.",
        WATERMELONICLE = "It makes me really cold, but it's tasty.",
        TRAILMIX = "Mixed nuts and stuff.",
        HOTCHILI = "YUM!  That's spicy!",
        GUACAMOLE = "It's a rather morbid take on the dish...",
		MONSTERMEAT = "This does not look very appetizing.",
		MONSTERMEAT_DRIED = "It's dried, but it doesn't have much else going for it.",
		MOOSE = "What is this thing?",
		MOOSEEGG = "That's one heck of an egg.",
		MOSSLING = "It's a little fluffy...  Thing...",
		FEATHERFAN = "Feather fan!",
		GOOSE_FEATHER = "It's so soft!",
		STAFF_TORNADO = "Time to bring the pane!",
		MOSQUITO =
		{
			GENERIC = "They like cactus juice too.",
			HELD = "Mosquitoes suck.",
		},
		MOSQUITOSACK = "Sure, it's not my blood, but it'll heal me.",
		MOUND =
		{
			DUG = "I should probably have more respect for the dead.",
			GENERIC = "I wonder what good stuff dead people leave behind?",
		},
		NIGHTLIGHT = "That's a creepy light.",
		NIGHTMAREFUEL = "It's like condensed insanity.",
		NIGHTSWORD = "A powerful figment of the imagination.",
		NITRE = "I've heard it has explosive potential.",
		ONEMANBAND = "It's like a country rock polka!",
		PANDORASCHEST = "What lies inside of this chest?",
		PANFLUTE = "A primitive but astounding instrument.",
		PAPYRUS = "Some paper.",
		PENGUIN = "Some flightless birds.",
		PERD = "Hey jerk!  Those are my berries!",
		PEROGIES = "Polish delight.",
		PETALS = "I'm eliminating the competition.",
		PETALS_EVIL = "These petals give off an eerie vibe.",
		PICKAXE = "I should craft a plan to start mining.",
		PIGGYBACK = "Even in death, he's a big help to me.",
		PIGHEAD = 
		{	
			GENERIC = "Well now that's just lovely.",
			BURNT = "I like my ham thoroughly cooked, but not like this!",
		},
		PIGHOUSE =
		{
			FULL = "I hear snoring, but I find it hard to believe that they're asleep.",
			GENERIC = "These pig houses aren't terribly made, surprisingly.",
			LIGHTSOUT = "Yeah, that's really neighborly of you.",
			BURNT = "You deserved it, you selfish pig.",
		},
		PIGKING = "The king of filth.",
		PIGMAN =
		{
			DEAD = "Well, he's dead.",
			FOLLOWER = "If you start feeding them, they'll never leave.",
			GENERIC = "Sentient pigs.  Good heavens.",
			GUARD = "Easy there, fellah.",
			WEREPIG = "As if the hounds weren't bad enough!",
		},
		PIGSKIN = "It's a shame I don't have the recipe for pork rinds.",
		PIGTENT = "It smells like someone's cooking ham in there.",
		PIGTORCH = "I'm a little scared knowing that they have fire.",
		PINECONE = 
		{
		    GENERIC = "It's kind of cute.",
		    PLANTED = "Grow big and strong, young tree.",
		},
		PITCHFORK = "I should take the ground and push it somewhere else.",
		PLANTMEAT = "This probably goes against at least 7 different morals.",
		PLANTMEAT_COOKED = "I'm not exactly sure what it is that I've done here.",
		PLANT_NORMAL =
		{
			GENERIC = "Such brilliant foliage.",
			GROWING = "It will take some time to grow.",
			READY = "It looks ready to be picked.",
			WITHERED = "It shriveled up and died from the heat.",
		},
		POMEGRANATE = "It reminds me of a bunch of clustered puss sores.",
		POMEGRANATE_COOKED = "Looks gross, tastes great.",
		POMEGRANATE_SEEDS = "Pomegranate seeds.",
		POND = "I can go for a while without water.",
		POOP = "I don't care if I AM a plant, I'm not eating poop.",
		FERTILIZER = "A bucket of poop.  Still not eating it.",
		PUMPKIN = "It's like my head, but spineless and orange!",
		PUMPKINCOOKIE = "I love cookies.",
		PUMPKIN_COOKED = "I should eat it before it becomes a carriage.",
		PUMPKIN_LANTERN = "The produce produces light.",
		PUMPKIN_SEEDS = "I've heard they're great toasted.",
		PURPLEAMULET = "I think I'm hearing things.",
		PURPLEGEM = "I wonder if it tastes like grape?",
		RABBIT =
		{
			GENERIC = "He's searching for veggies to munch.",
			HELD = "I guess he doesn't like it when I hold him.",
		},
		RABBITHOLE = 
		{
			GENERIC = "I've heard that rabbit holes can branch off dozens of times.",
			SPRING = "The rabbits don't want anyone learning their secrets.",
		},
		RAINOMETER = 
		{	
			GENERIC = "Now I can predict when it will rain!",
			BURNT = "Now I can't predict anything.",
		},
		RAINCOAT = "Keeps the rain off my torso.",
		RAINHAT = "My flower won't get sun, but at least it won't drown.",
		RATATOUILLE = "I think it's from France, or something.",
		RAZOR = "I wish I could grow a moustache...",
		REDGEM = "It gives off a warm sensation.",
		RED_CAP = "A red mushroom.",
		RED_CAP_COOKED = "A cooked red mushroom.",
		RED_MUSHROOM =
		{
			GENERIC = "This is a mushroom, I think.",
			INGROUND = "You've gotta come out sometime.",
			PICKED = "Don't worry, it'll grow back.",
		},
		REEDS =
		{
			BURNING = "I'm glad that's not me.",
			GENERIC = "A bunch of marsh reeds.",
			PICKED = "No more reeds left to pick.",
		},
        RELIC = 
        {
            GENERIC = "An ancient relic.",
            BROKEN = "I can't do anything with this.",
        },
        RUINS_RUBBLE = "I think I can fix this.",
        RUBBLE = "It's a bunch of rock fragments.",
		RESEARCHLAB = 
		{	
			GENERIC = "It makes science, apparently.",
			BURNT = "Well, I can't use it anymore...",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "A better version of the science machine.",
			BURNT = "It's gone now.  Pity.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "What manner of sorcery is this?!",
			BURNT = "It was burned alive for being evil witchcraft.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Prestihatiwhat-now?",
			BURNT = "The name is still stupid, but now it's burnt and stupid.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "I don't believe I recognize this fellow.",
			BURNT = "Whoever he was, he's burnt now.",
		},
		RESURRECTIONSTONE = "There are odd markings etched into this stone.",
		ROBIN =
		{
			GENERIC = "Reminds me of the sunsets back home.",
			HELD = "How about a hug?",
		},
		ROBIN_WINTER =
		{
			GENERIC = "I wish I had feathers like you.",
			HELD = "Too bad he won't keep me warm.",
		},
		ROBOT_PUPPET = "It looks like it's trapped!",
		ROCK_LIGHT =
		{
			GENERIC = "A lava pit.  I hope I don't fall in.",
			OUT = "It appears fragile.",
			LOW = "Uh-oh, it's crusting over.",
			NORMAL = "This feels nice.",
		},
		ROCK = "These are everywhere.",
		ROCK_ICE = 
		{
			GENERIC = "It's a miniature glacier!",
			MELTED = "It's just a puddle now.",
		},
		ROCK_ICE_MELTED = "There's no ice to take.",
		ICE = "I don't like being cold.",
		ROCKS = "A basic building material.",
        ROOK = "Have I mentioned that I do not care for chess?",
		ROPE = "Rope is always useful.",
		ROTTENEGG = "I'm sure it's still good for something.",
		SANITYROCK =
		{
			ACTIVE = "What an odd stone.",
			INACTIVE = "It used to be bigger, didn't it?",
		},
		SAPLING =
		{
			BURNING = "Oh my, what a fire!",
			WITHERED = "It just can't stay alive in this heat.",
			GENERIC = "These trees are cursed with dwarfism.",
			PICKED = "Not even a twig left.",
		},
		SEEDS = "Plant eggs.",
		SEEDS_COOKED = "Mmm!  Toasty!",
		SEWING_KIT = "Well, I've got plenty of needles.",
		SHOVEL = "I can dig it.",
		SILK = "It's so smooth and sticky.",
		SKELETON = "The inside structure of a human.  Pity.",
		SKELETON_PLAYER = "The inside structure of a...  Wait, what?!",
		SKULLCHEST = "Skulls for the skull chest!",
		SMALLBIRD =
		{
			GENERIC = "It's got a long way to go before it's a tallbird.",
			HUNGRY = "The poor thing looks hungry.",
			STARVING = "I need to feed it something, quick.",
		},
		SMALLMEAT = "It's meat from a small animal.",
		SMALLMEAT_DRIED = "Small dried meat.",
		SPEAR = "I like pointy things.",
		SPIDER =
		{
			DEAD = "Good.",
			GENERIC = "Spiders are disgusting.",
			SLEEPING = "They're even gross when they're asleep.",
		},
		SPIDERDEN = "Nasty webbing.",
		SPIDEREGGSACK = "I shouldn't be carrying these.",
		SPIDERGLAND = "This is a spider's organ.  Gross.",
		SPIDERHAT = "A reminder that spiders should never be this big.",
		SPIDERQUEEN = "Oh-no.  This is not good.",
		SPIDER_WARRIOR =
		{
			DEAD = "One less worthless spider.",
			GENERIC = "Trained in the art of being mean and gross.",
			SLEEPING = "Nasty thing.",
		},
		SPOILED_FOOD = "I think I just saw it move.",
		STATUEHARP = "This is not positive foreshadowing.",
		STATUEMAXWELL = "A stone-cold body to match his heart.",
		STINGER = "That's cute.",
		STRAWHAT = "Nothing beats a good old fashioned straw hat.",
		STUFFEDEGGPLANT = "This is probably the fanciest thing I will ever eat.",
		SUNKBOAT = "Well, that's just great.",
		SWEATERVEST = "You can tell that it's mine because of all the holes.",
		REFLECTIVEVEST = "Normally, I want all the sun I can get.",
		HAWAIIANSHIRT = "Now I have more flowers that any cactus!",
		TAFFY = "It's really tasty, but it sticks to my insides.",
		TALLBIRD = "What a tall bird!",
		TALLBIRDEGG = "It may hatch with some time.",
		TALLBIRDEGG_COOKED = "Tastes great, and it was quite an effort to get.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "The egg is shivering.",
			GENERIC = "It's starting to hatch.",
			HOT = "That egg needs to be cooled down!",
			LONG = "It doesn't appear close to hatching.",
			SHORT = "It's about to hatch!",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Look at the size of that egg!",
			PICKED = "There's nothing in here.",
		},
		TEENBIRD =
		{
			GENERIC = "An adolescent bird.",
			HUNGRY = "I need to find you some food.",
			STARVING = "Don't even think about it, bird.",
		},
		TELEBASE =
		{
			VALID = "It's fully functional!",
			GEMS = "I need to add more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "It looks ready to me.",
			GEMS = "I have to put a gem in there.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "I can use this to surpass time and space, it seems!",
			GENERIC = "This looks like a means of traveling to another world!",
			LOCKED = "It doesn't have all the parts yet.",
			PARTIAL = "It's not done yet, but it's close!",
		},
		TELEPORTATO_BOX = "This looks like a part of something bigger...",
		TELEPORTATO_CRANK = "This looks like a part of something bigger...",
		TELEPORTATO_POTATO = "This looks like a part of something bigger...",
		TELEPORTATO_RING = "This looks like a part of something bigger...",
		TELESTAFF = "Teleporting is always fun.",
		TENT = 
		{
			GENERIC = "Even cacti need to sleep.  Well, I do anyway.",
			BURNT = "Nowhere to sleep now.",
		},
		SIESTAHUT = 
		{
			GENERIC = "It's a nice place to take a mid-day snooze.",
			BURNT = "So much for naptime.",
		},
		TENTACLE = "What does the rest of it look like?",
		TENTACLESPIKE = "Those are some nasty spikes.  Mine are much cleaner.",
		TENTACLESPOTS = "What a lovely pattern!",
		TENTACLE_PILLAR = "A big tentacle pillar.",
		TENTACLE_PILLAR_ARM = "Is this thing just made up of nothing but tentacles?!",
		TENTACLE_GARDEN = "More tentacles.  Hooray.",
		TOPHAT = "This is a brand new hat, and there are already holes in it.",
		TORCH = "It'll help me see at night.",
		TRANSISTOR = "I can hear it buzzing.",
		TRAP = "What CAN'T you make out of grass?",
		TRAP_TEETH = "Someone's going to have a very bad day.",
		TRAP_TEETH_MAXWELL = "Nice try, Maxwell!",
		TREASURECHEST = 
		{
			GENERIC = "I like big chests, I cannot lie.",
			BURNT = "The trunk is gone now.",
		},
		TREASURECHEST_TRAP = "Almost TOO convenient...",
		TREECLUMP = "I think someone wants to hinder my progress.",
		TRINKET_1 = "The marbles have become a singularity now.",
		TRINKET_10 = "Now I can stop shoving food through my eye-holes.",
		TRINKET_11 = "Beep boop, son.  Beep boop.",
		TRINKET_12 = "What did this come from?",
		TRINKET_2 = "It's a shame it's a fake, I could use some music.",
		TRINKET_3 = "There's no getting that knot out.",
		TRINKET_4 = "A gnome, but what is he guardin'?",
		TRINKET_5 = "I wish I could rocket outta here.",
		TRINKET_6 = "I wish they were still useable.",
		TRINKET_7 = "From a simpler time.",
		TRINKET_8 = "I can put it in my eye and pretend I'm a pirate.",
		TRINKET_9 = "Button, button, who's got the button?",
		TRUNKVEST_SUMMER = "Forest chic.",
		TRUNKVEST_WINTER = "The heat keeps escaping through all the holes.",
		TRUNK_COOKED = "It's surprisingly delicious.",
		TRUNK_SUMMER = "I'll have to clean it out first.",
		TRUNK_WINTER = "It's thick and hairy.",
		TUMBLEWEED = "Ah, it feels good to see these again.",
		TURF_CARPETFLOOR = "It has a nice plush feet under my roots.",
		TURF_CHECKERFLOOR = "It makes me feel like a king.",
		TURF_DIRT = "Good ol' fashioned dirt.",
		TURF_FOREST = "Ground from the forest.",
		TURF_GRASS = "They don't make grass like this anymore.",
		TURF_MARSH = "Wet and soppy ground.",
		TURF_ROAD = "I took the road less traveled and put it in my pocket.",
		TURF_ROCKY = "It's a rocky road.",
		TURF_SAVANNA = "It's an old pioneer trick.",
		TURF_WOODFLOOR = "Nothing beats the hardwood.",
		TURKEYDINNER = "Thanks.",
		TWIGS = "A bunch of little sticks.",
		UMBRELLA = "Be warned, I am dangerous with an umbrella.",
		GRASS_UMBRELLA = "I can kick some serious tail with a parasol.  No joke.",
		UNIMPLEMENTED = "I don't think this is finished.  Enter at your own risk!",
		WAFFLES = "Needs more syrup.",
		WALL_HAY = 
		{	
			GENERIC = "It's not much, but it's something.",
			BURNT = "Now it's nothing.",
		},
		WALL_HAY_ITEM = "Not very sturdy.",
		WALL_STONE = "It's a pretty decent wall.",
		WALL_STONE_ITEM = "It holds up fairly well.",
		WALL_RUINS = "A sturdy ancient wall.",
		WALL_RUINS_ITEM = "An oldie but a goodie.",
		WALL_WOOD = 
		{
			GENERIC = "It's pretty sturdy, but watch those flames.",
			BURNT = "Told you so.",
		},
		WALL_WOOD_ITEM = "It's made of wood!",
		WALRUS = "Trust me, you wouldn't like cactus.",
		WALRUSHAT = "Well, now there are holes in it.",
		WALRUS_CAMP =
		{
			EMPTY = "Seems that this was someone's camp.",
			GENERIC = "It's too bad I can't join them.",
		},
		WALRUS_TUSK = "It would make great piano keys.",
		WARG = "That's a big hound.",
		WASPHIVE = "Those aren't friendly bees...",
		WATERMELON = "It's like a spineless cactus.",
		WATERMELON_COOKED = "Tastes great when warmed, actually.",
		WATERMELONHAT = "I don't like being sticky...",
		WETGOOP = "It's barely edible.",
		WINTERHAT = "I love the little snowflake pattern on it.",
		WINTEROMETER = 
		{
			GENERIC = "It'll warn me when it's about to snow.",
			BURNT = "It won't measure anything now.",
		},
		WORMHOLE =
		{
			GENERIC = "I can hear it gurgling...",
			OPEN = "Should I jump in?",
		},
		WORMHOLE_LIMITED = "I think I'll kill the poor thing if I go through it.",
		ACCOMPLISHMENT_SHRINE = "I accomplished a thing!  I AM GREAT!",        
		LIVINGTREE = "I have no problem cutting it down.",
		ICESTAFF = "It feels cold when I touch it.",
	},
	DESCRIBE_GENERIC = "I...  Don't know what this is.",
	DESCRIBE_TOODARK = "I can't see!",
	DESCRIBE_SMOLDERING = "I smell smoke...  This is about to get ugly.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "I could taste the feathers on that one.",
	},
}
